server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  #flyway:
  #  url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
  #  schemas: mock
  #  user: ${POSTGRES_USER}
  #  password: ${POSTGRES_PASSWORD}

  jpa:
    #show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: manager

springfox:
  documentation:
    swagger-ui:
      base-url: manager-docs
    swagger:
      v2:
        path: manager-docs