# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test
  prepare-environment:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Delete old containers
        run: docker rm -vf $(docker ps -aq)
      - name: Delete old images
        run: docker rmi -f $(docker images -aq)
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose
        run: docker-compose up -d
