# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Delete old containers
        run: docker rm $(docker ps -aq) -f
      - name: Delete old images
        run: docker rmi -f $(docker images -aq)
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose
        run: docker-compose up -d
